//
// Created by Plutex on 2026-01-24.
//

#include "EditorPythonManager.h"
#include "PluEngine/FrameDemand.h"

#include "EditorAppContext.h"
#pragma warning(push, 0)
#include "pybind11/pybind11.h"
#include "pybind11/embed.h"
#pragma warning(pop)
#include "Python.h"
#include "Managers/Project/EditorProjectManager.h"

extern Plu::EditorAppContext* gEditorAppContext;
extern Plu::ApplicationInfo* gApplicationInfo;

static std::atomic<bool> gScriptsReloadNeeded = false;

void Plu::EFSWScriptsUpdateListener::handleFileAction(efsw::WatchID watchid, const std::string &dir,
                                                      const std::string &filename, efsw::Action action, std::string oldFilename)
{
	switch (action) {
		case efsw::Action::Add:
		case efsw::Action::Modified:
		{
			// Only source files count. Importing the project writes __pycache__/*.pyc back into the
			// watched tree, so an unfiltered watch re-armed the reload with every reload it caused —
			// the editor kept re-importing (and recreating the scene's python objects) forever on a
			// project nobody was editing.
			if (dir.find("__pycache__") != std::string::npos) break;
			if (filename.size() < 3 || filename.compare(filename.size() - 3, 3, ".py") != 0) break;
			// Same file RunProjectScripts skips: it is generated by the editor (asset dictionary), so
			// writing it must not count as the user editing a script.
			if (!GeneratedAssetDictionaryFile.empty() && filename == GeneratedAssetDictionaryFile) break;
			gScriptsReloadNeeded.store(true);
			break;
		}
		case efsw::Action::Delete:
			PLU_CORE_WARN("Removing Scripts in Runtime is not implemented! You may run in to Undefined Behaviour or it may work perfectly, Editor restart recommended though");
			break;
		case efsw::Action::Moved:
			break;
	}
}

Plu::EditorPythonManager::EditorPythonManager()
{
	if (!Py_IsInitialized()) {
		Py_Initialize();
	}
	pybind11::module_ main_module = pybind11::module_::import("__main__");
}

Plu::EditorPythonManager::~EditorPythonManager()
{
	Py_Finalize();
}

void Plu::EditorPythonManager::RunProjectScripts()
{
	for (const auto& script : std::filesystem::recursive_directory_iterator(gEditorAppContext->EditorProjectManager->GetProjectScriptsDirectory().CStr())) {
		PathW scriptPath = script.path().wstring().c_str();
		if (scriptPath.GetStem() == gEditorAppContext->EditorProjectManager->GetProjectName()) continue;
		if (scriptPath.GetExtension() != L".py") continue;
		RunScript(scriptPath, gEditorAppContext->EditorProjectManager->GetProjectScriptsDirectory(), "");
	}
}

void Plu::EditorPythonManager::ClearProjectScripts()
{
	mUserModules.PushBack(gEditorAppContext->EditorProjectManager->GetProjectName().ToNarrow());
	pybind11::dict modules = pybind11::module_::import("sys").attr("modules");
	for (const auto& name : mUserModules) {
		if (modules.contains(name.CStr())) {
			modules.attr("pop")(name.CStr());
		}
	}
	mUserModules.Clear();
}

void Plu::EditorPythonManager::InitializeScriptsWatcher()
{
	if (!mFileWatcher) {
		mFileWatcher = new efsw::FileWatcher();
		mListener = new EFSWScriptsUpdateListener();
		mListener->GeneratedAssetDictionaryFile = (gEditorAppContext->EditorProjectManager->GetProjectName().ToNarrow() + ".py").CStr();
		mProjectScriptsWatchId = mFileWatcher->addWatch(gEditorAppContext->EditorProjectManager->GetProjectScriptsDirectory().ToString().ToNarrow().CStr(), mListener, true);
		std::string error = efsw::Errors::Log::getLastErrorLog();
		if (!error.empty()) {
			PLU_ERROR("{}", error.c_str());
		}
		if (mFileWatcher) {
			mFileWatcher->watch();
		}
	}
}

void Plu::EditorPythonManager::CheckForScriptsChanges()
{
	// Cleared before the reload, not after: the reload itself may legitimately trip the watcher again
	// (a file saved while it runs), and that event must survive into the next check. Never clearing it
	// at all — which is what this used to do — meant one file save put the editor into a permanent
	// reload-every-100-frames loop.
	if (!gScriptsReloadNeeded.exchange(false)) return;
	// May be running from the idle tick (power saving): the reload changes what the UI shows.
	RequestRedraw();
	ClearProjectScripts();
	RunProjectScripts();
}

bool Plu::EditorPythonManager::RunScript(PluUUID uuid)
{
	return false;
}

bool Plu::EditorPythonManager::RunScript(PathW path, PathW workDir, String args)
{
	try {
		// 1. Ustawienie katalogu roboczego
		PathW orging = std::filesystem::current_path().wstring().c_str();
		std::filesystem::current_path(workDir.CStr());

		pybind11::module_ sys = pybind11::module_::import("sys");

		// 1. sys.path
		pybind11::list path_list = sys.attr("path");
		path_list.insert(0, path.GetParentPath().CStr());

		// 2. sys.argv - upewniamy się, że to czysta lista stringów
		pybind11::list py_argv;
		py_argv.append(pybind11::str(path.ToString().ToNarrow().CStr()));

		std::stringstream ss(args.CStr());
		std::string arg;
		while (ss >> arg) {
			py_argv.append(pybind11::str(arg));
		}
		sys.attr("argv") = py_argv;

		// 3. Przekierowanie stdout/stderr bez operatora _a
		pybind11::module_ builtins = pybind11::module_::import("builtins");
		builtins.attr("print_to_plu") = pybind11::cpp_function([this](std::string m, bool isError) {
			if (isError) PLU_ERROR("[Python] {}", m);
			else PLU_INFO("[Python] {}", m);
		});

		pybind11::exec(R"(
import sys
import builtins

class LogRedirector:
    def __init__(self, callback):
        self.callback = callback
    def write(self, m):
        msg = m.strip()
        if msg: self.callback(msg)
    def flush(self): pass

# Pobieramy funkcję bezpośrednio z builtins, żeby uniknąć problemów z zasięgiem
sys.stdout = LogRedirector(lambda msg: builtins.print_to_plu(msg, False))
sys.stderr = LogRedirector(lambda msg: builtins.print_to_plu(msg, True))
)");

		// 4. Uruchomienie skryptu
		std::string moduleName = path.GetStem().ToNarrow().CStr();

		// Usuń stary moduł z cache jeśli istnieje
		pybind11::dict modules = sys.attr("modules");
		if (modules.contains(moduleName)) {
			modules.attr("pop")(moduleName);
		}

		pybind11::module_::import(moduleName.c_str());
		PLU_TRACE("Run Script {}", moduleName.c_str());

		// Dodaj do listy tylko jeśli jeszcze nie ma
		if (!mUserModules.Contains(path.GetStem().ToNarrow())) {
			mUserModules.PushBack(path.GetStem().ToNarrow());
		}

		return true;
	} catch (const pybind11::error_already_set& e) {
		PLU_ERROR("Python Error: {}", e.what());
		return false;
	} catch (const std::exception& e) {
		PLU_ERROR("System Error: {}", e.what());
		return false;
	}
}
